<<<<<<< HEAD
# Specifies to Travis the language to use
language: node_js
# Use the latest version of node
node_js:
  - "node"

# Caches the node_modules directory so travis doesn't install the same thing after every commit.
cache:
  directories:
    - node_modules

# Run these scripts
script:
  - ./build/build-and-test.sh
=======
# Specify the language used to Travis
language: node_js
# Specify the node version (to latest)
node_js:
  - "node"
# Cache these directories so the same versions are not run/installed every time
cache:
  directories:
    - "node_modules"
install: true
# Run these scripts
script:
  - ./build/build-and-test.sh
>>>>>>> demo01c
